# Generated by Django 5.0.1 on 2024-01-13 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubbotnikMain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='pollutionLevel',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
        migrations.AddField(
            model_name='marker',
            name='signed',
            field=models.ManyToManyField(related_name='markers', to=settings.AUTH_USER_MODEL),
        ),
    ]
