# Generated by Django 5.0.1 on 2024-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubbotnikMain', '0004_alter_marker_description_alter_marker_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
