# Generated by Django 5.0.1 on 2024-01-13 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubbotnikMain', '0006_alter_marker_photo_alter_marker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='opened',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='signed',
            field=models.ManyToManyField(blank=True, null=True, related_name='markers', to=settings.AUTH_USER_MODEL),
        ),
    ]
