# Generated by Django 5.0.1 on 2024-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubbotnikMain', '0007_alter_marker_opened_alter_marker_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.CharField(max_length=200),
        ),
    ]
